#pragma once
#include <Windows.h>

enum : WORD
{
    EN_PACKET_CS_CHAT_REQ_LOGIN = 1,
    EN_PACKET_CS_CHAT_RES_LOGIN = 2,
    EN_PACKET_CS_CHAT_REQ_SECTOR_MOVE = 3,
    EN_PACKET_CS_CHAT_RES_SECTOR_MOVE = 4,
    EN_PACKET_CS_CHAT_REQ_MESSAGE = 5,
    EN_PACKET_CS_CHAT_RES_MESSAGE = 6,
    EN_PACKET_CS_CHAT_REQ_HEARTBEAT = 7,
    EN_PACKET_SS_MONITOR_LOGIN = 20001,
    EN_PACKET_SS_MONITOR_DATA_UPDATE = 20002,
};